# Build the website and pushes it to the gh-pages branch
name: Publish
on:
  push:
    branches:
      - 'master'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - name: Remove all files except dist
        run: |
          mv docs/.vuepress/dist dist
          rm -r -f -v !("dist")
      - name: Commit to gh-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git fetch
          git checkout --orphan gh-pages
          git pull origin gh-pages || echo "Cannot pull. Maybe the branch does not exist yet?"
          rm -v !("dist")
          mv dist/* .
          git reset
          git add *
          git diff --quiet && git diff --staged --quiet || git commit -am "Build new version of website"
          git push --set-upstream origin gh-pages